### PR TITLE
Add cmd to build typescript and javascript

### PR DESCRIPTION
**Pull request by cbohiptest**
@jbpros and @karamosky you have more experience than me with typescript : the change allow to compile the react-gherkin-editor, but to use it with the gherkin editor I had to change most of the paths. Any idea to avoid all these changes on the paths ?

### CODE REVIEW

**Comment by mcoqblin-hiptest** [comment]
The problem is that module paths are supposed to be relative.

We are using the `module-resolver` Babel plugin which transforms absolute paths to relative paths. However this does not apply to types generated using the typescript CLI.

Unless there is some way for typescript to resolve modules (like webpack and Jest currently do), a solution could be to first transpile `src` into a `tmp` folder using Babel and **only** module-resolver, then run both `yarn build:js` and `yarn build:types` on the `tmp` folder.

**Comment by jbpros** [comment]
Why are we using that non-standard module resolution?

**Comment by mcoqblin-hiptest** [comment]
Because it's ugly. Webpack and Jest both provide a way to specify where to resolve modules from (on top of node_modules), and a lot of projects make use of that.

I forgot to mention that the other solution is to indeed have relative paths as they have been fixed by @cbohiptest

**Comment by karamosky** [comment]
I vote for the removal of non-standard module resolution from this package as it brings issues. (@mcoqblin-hiptest It's ugly yes but should we pay the price of this beauty? ) :)

**Comment by jbpros** [comment]
Ugliness is very subjective ;) I'm personally fine with relative paths. Practically, our IDEs are good at handling those out of the box, even when moving tons of files at once.

This non-standard module resolution introduces avoidable complexity, imho. I vote for going back to regular Node's commonjs module resolution.

**Comment by mcoqblin-hiptest** [comment]
You misunderstood the purpose of my previous comment. I'm not trying to defend that design choice, just to justify it since you asked 😅

I'm completely okay with changing that since it's gonna be a mess to manage with typescript.

**Comment by mcoqblin-hiptest** [comment]
It may be wise to keep that resolution for Jest though.
This would allow tests to refer to components directly in the src folder. Fixing tests without it means changing all imports to relative paths (from components/GherkinEditor, that would be ../../../src/components/GherkinEditor). That is more maintenance.

**Comment by mcoqblin-hiptest** [comment]
I'll take a look, this is probably a problem with mocks. I had problems with these tests when moving them yesterday.

**Pull request merged**
